# Docker para Broker RabbitMQ

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
      - "8883:8883"
      - "25672:25672"
      - "4369:4369"
    restart: always  # Opcional: reiniciar siempre el contenedor en caso de errores