# Docker para Broker RabbitMQ

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "80:15672"
      - "1883:1883"
    restart: always  # Opcional: reiniciar siempre el contenedor en caso de errores