# Docker para MySQL y PhpMyAdmin :)

version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "6606:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
