version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Kokun
      MYSQL_USER: Goku
      MYSQL_PASSWORD: Kokun
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Kokun
      MYSQL_USER: Goku
      MYSQL_PASSWORD: Kokun
    volumes:
      - phpmyadmin_sessions:/sessions

volumes:
  mysql_data:
  phpmyadmin_sessions:
